var en_US={
    navHome:"HOME",
    navAbout:"ABOUT US",
    navProduct:"PRODUCT",
    navEvent:"EVENT",
    navContact:"CONTACT",
    footAddr:"Address",
    footAddr2:"Room L307-308,Hopson Fortune Plaza,",
    footAddr2_5:" No.223 Building, No.28 Guangqu Road",
    footAddr3:"Chaoyang District, Beijing",
    footSlogan1:"Make quality of life",
    footSlogan2:"Leading the fashion industry",
    footSlogan3:"Keep the customer satisfaction and market recognition",
    footSlogan4:"Pioneer and steady, quality content and fashion trend",
    pro_main:"Products",
    pro_main1:"Mainly : sweater, shirt, windbreaker, jacket etc.",
    pro_main2:"To make people enjoy the life experience of fashion",
    pro_class1:"Leather products",
    pro_class1_:"Mainly include: sweater, shirt, windbreaker, jacket etc.",
    pro_class2:"textile",
    pro_class2_:"There are: Hat :Bluetooth hat, gloves :Bluetooth gloves, scarves,belts.",
    pro_class3:"Fashion electronic",
    pro_class3_:": Mobile power, Electronic bracelet",
    pro_class4_:"Mainly include: Mat, Cushion, Fashion bags, Travel kit",
    pro_pic:"Recent Products",
    about_header:"About us",
    about_header1:"The innovation of product design, to meet customer needs, to become the industry pioneer, leading the fashion industry.",
    about_header2:"To create an exclusive personal style",
    about_header3:"Product highlights and advantages",
    about_header4:"Leather products are the company's advantage products, from design to production have a unique style",
    about_header5:"Innovation is the soul of design",
    about_header6:"Leather products are the company's advantage products, from design to production have a unique style,Innovation is the soul of design.Companies adhering to the original idea at the same time, more adhere to the design of innovative ideas, has formed a research and development designers as the core management team. Company based on the market, through the research design, the customer's product concepts concrete, with innovative design innovation motivity of enterprise cohesion, with higher view dialysis in the design process, with reasonable price, excellent working efficiency, thoughtful customer service, rigorous design process for customers to provide high-quality products and design services, the formation of the company of great advantage.",
    about_main:"Enterprise Opinion",
    about_main1:"Innovative product design to meet customer needs",
    about_main2:"To become the industry pioneer, leading the fashion industry",
    about_main1_1:"Committed to providing professional, high-quality clothing design and production, so that people enjoy the forefront of fashion life experience.",
    about_main2_2:"Meet the full range of customer demands, for people to create a unique personal style.",
    about_main2_3:"Synchronized with the world in the creation of popular fashion, but also brings the exquisite quality and service.",
    about_main2_1:"Combined with the most important elements of the selection of the new market demands, the company's brand image into product design, strengthen design style, highlight the product style, to consolidate corporate positioning.",
    about_main1_2:"Will be excellent product design, rigorous product mix design, and innovative product concept integration, after years of precipitation accumulation, the company's products in the fierce competition in the market to stand out.",
    about_main1_3:"Leading the fashion design elements",
    about_team:"Enterprise Structure",
    about_tree:"",
    home_header:"Company Profile",
    home_header1:"The design and production of specialized, high quality clothing",
    home_header2:"Reasonable price, excellent work efficiency, considerate customer service, rigorous design",
    home_header3:"Services provided by the company rely on professional and perfect design process, able to provide customers from the market survey, preliminary analysis, design, structural design, mold processing, batch production and sales of the station design services.",
    btn_more:"MORE",
    home_serve:"Products",
    home_serve1:"We adhering to the original idea at the same time, more adhere to the design of innovative ideas, innovation and cohesion with the design of the original driving force",
    home_serve2:"Leather products is the advantage of the company's products, from design to production has a unique style, has been fully recognized by the customers of the company, the products within the reporting period sales accounted for ratio is the highest, is worthy of the name products.",
    home_serve3:"With innovative thinking and continuous improvement of the design concept.",
    home_team:"Cooperative Partner",
    home_team1:"Have a passionate young team",
    home_team2:"With innovative thinking and continuous improvement of the design concept",
    home_team3:"Has formed a research and development designers as the core management team. Company based on the market, through the research design, the customer's product concepts concrete, with innovative design innovation motivity of enterprise cohesion, with higher view dialysis in the design process, with reasonable price, excellent working efficiency, thoughtful customer service, rigorous design process for customers to provide high-quality products and design services, the formation of the company of great advantage.",
    contact_header:"Contact Us",
    home_slogan1:"With quality of life",
    home_slogan2_1:"To become the industry leader",
    home_slogan2_2:"Leading the fashion industry",
    home_slogan3_1:"Pioneering and steady",
    home_slogan3_2:"Quality content and fashion trend",
    home_pro1:"Clothing",
    home_pro1_:"Sweater",
    home_pro2:"Accessory",
    home_pro2_:"Hat,Glove,Scarf,Bag,Belt",
    home_pro3:"Digital",
    home_pro3_:"Mobile power,Electronic Bracelet",
    home_pro4:"Home",
    home_pro4_:"Mat,Cushion,Travel kit",
    contact_1:"Address",
    contact_1_1:"Room L307-308,Hopson Fortune Plaza, No.223 Building,",
    contact_1_2:"No.28 Guangqu Road,Chaoyang District, Beijing",
    contact_2:"Telephone: (+86)010-56916479",
    contact_3:"FAX：(+86)010-56916478-811",
    contact_4:'E-mail: <\a href="mailto:service@sherrytek.com">service@sherrytek.com<\/a>',
    home_news:"News"
}
