var en_US={
    navHome:"HOME",
    navAbout:"ABOUT US",
    navProduct:"PRODUCT",
    navEvent:"ANNOUNCEMENT",
    navContact:"CONTACT",
    footAddr:"Address",
    footAddr2:"Room L307-308,Hopson Fortune Plaza,",
    footAddr2_5:" No.223 Building, No.28 Guangqu Road",
    footAddr3:"Chaoyang District, Beijing",
    footSlogan1:"We want to lead a high quality life. ",
    footSlogan2:"Vying for the industry pioneer and lead the industry trends.",
    footSlogan3:"Keep the customer satisfaction and market recognition.",
    footSlogan4:"Pioneer and steady, quality content and fashion trend.",
    pro_main:"Products",
    pro_main1:"Mainly : sweater, shirt, windbreaker, jacket etc.",
    pro_main2:"We provide professional design for high quality garment and accessaries ,offer reasonable price for products . the remarkable efficiency and thoughtful customer.",
    pro_class1:"Leather products",
    pro_class1_:"Mainly include: sweater , shirt ,trench coat, outerwear and so on.",
    pro_class2:"Accessary",
    pro_class2_:"Mainly include: Bluetooth hat, Bluetooth gloves, scarves,belts.",
    pro_class3:"Fashion electronic",
    pro_class3_:"Mainly include: Mobile power, Electronic bracelet",
    pro_class4_:"Mainly include: Mat, Cushion, Fashion bags, Travel kit",
    pro_pic:"Recent Products",
    about_header:"About us",
    about_header1:"The innovation of product design, to meet customer needs, to become the industry pioneer, leading the fashion industry.",
    about_header2:"To make personal style",
    about_header3:"We have own product highlights and design advantages.",
    about_header4:"Leather products are the company's advantage products, from design to production have a unique style",
    about_header5:"Innovation is the soul of design",
    about_header6:"Leather products are the company's advantage products, from design to production have a unique style,Innovation is the soul of design.Companies adhering to the original idea at the same time, more adhere to the design of innovative ideas, has formed a research and development designers as the core management team. Company based on the market, through the research design, the customer's product concepts concrete, with innovative design innovation motivity of enterprise cohesion, with higher view dialysis in the design process, with reasonable price, excellent working efficiency, thoughtful customer service, rigorous design process for customers to provide high-quality products and design services, the formation of the company of great advantage.",
    about_main:"Enterprise Opinion",
    about_main1:"Innovative product design to meet customer needs",
    about_main2:"To become the industry pioneer, leading the fashion industry",
    about_main1_1:"Committed to providing professional, high-quality clothing design and production, so that people enjoy the forefront of fashion life experience.",
    about_main2_2:"Meeting the total demand of customer , to create exclusive personal style.",
    about_main2_3:"Synchronized with the world in the creation of popular fashion, but also brings the exquisite quality and service.",
    about_main2_1:"Combined with the most important elements of the selection of the new market demands, the company's brand image into product design, strengthen design style, highlight the product style, to consolidate corporate positioning.",
    about_main1_2:"Will be excellent product design, rigorous product mix design, and innovative product concept integration, after years of precipitation accumulation, the company's products in the fierce competition in the market to stand out.",
    about_main1_3:"Leading the fashion design elements",
    about_team:"Enterprise Structure",
    about_tree:"",
    home_header:"Profile(Stock Code 870099)",
    home_header1:"The design and production of specialized, high quality clothing",
    home_header2:"Reasonable price, excellent work efficiency, considerate customer service, rigorous design",
    home_header3:"Services provided by the company rely on professional and perfect design process, able to provide customers from the market survey, preliminary analysis, design, structural design, mold processing, batch production and sales of the station design services.",
    btn_more:"MORE",
    home_serve:"Products",
    home_serve1:"We adhering to the original idea at the same time, more adhere to the design of innovative ideas, innovation and cohesion with the design of the original driving force",
    home_serve2:"Leather products is the advantage of the company's products, from design to production has a unique style, has been fully recognized by the customers of the company, the products within the reporting period sales accounted for ratio is the highest, is worthy of the name products.",
    home_serve3:"With innovative thinking and continuous improvement of the design concept.",
    home_team:"Cooperative Partner",
    home_team1:"We have a passionate young team!",
    home_team2:"With innovative thinking and continuous improvement of the design concept.",
    home_team3:"We have formed a research and development designers as the core management team. Company based on the market, through the research design, the customer's product concepts concrete, with innovative design innovation motivity of enterprise cohesion, with higher view dialysis in the design process, with reasonable price, excellent working efficiency, thoughtful customer service, rigorous design process for customers to provide high-quality products and design services, the formation of the company of great advantage.",
    contact_header:"Contact Us",
    home_slogan1:"We want to lead a high quality life!",
    home_slogan2_1:"We want to become the industry leader.",
    home_slogan2_2:"Leading the fashion industry",
    home_slogan3_1:"Pioneering and steady",
    home_slogan3_2:"Quality content and fashion trend",
    home_pro1:"Clothing",
    home_pro1_:"Sweater",
    home_pro2:"Accessory",
    home_pro2_:"Hat、Glove、Scarf、Bag、Belt.",
    home_pro3:"Digital",
    home_pro3_:"Mobile power、Electronic Bracelet.",
    home_pro4:"Home",
    home_pro4_:"Mat,Cushion,Travel kit",
    home_news1:"Directors Appoint Announcement",
    home_news1_:"09:00 - 10:00 | 02-07-2017",
    home_news1__:"Directors Appoint Announcement",
    home_news2:"The resolutions of shareholders' meeting",
    home_news2_:"10:00 - 12:00 | 02-07-2017",
    home_news2__:"Shareholders' meeting",
    home_news3:"Announcements of the  shareholders' general meeting",
    home_news3_:"09:00 - 10:00 | 01-11-2017",
    home_news3__:"Announcements of the extraordinary shareholders' general meeting",
    home_news4:"Connection transaction announcement",
    home_news4_:"10:00 - 11:00 | 01-11-2017",
    home_news4__:"Connection transaction announcement",
	home_news0:"Science park leadership inspection work",
    home_news0_:"10:00 - 12:00 | 03-15-2017",
    home_news0__:"Welcome",
    contact_1:"Address",
    contact_1_1:"Room L307-308,Hopson Fortune Plaza, No.223 Building,",
    contact_1_2:"No.28 Guangqu Road,Chaoyang District, Beijing",
    contact_2:"TEL: (+86)010-56916479",
    contact_3:"FAX：(+86)010-56916478-811",
    contact_4:'E-mail: <\a href="mailto:service@sherrytek.com">service@sherrytek.com<\/a>',
    home_news:"Announcement",
    event_header1:"Directors Appoint Announcement",
    event_header1_:"http://www.neeq.com.cn/disclosure/2017/2017-02-07/1486453071_450956.pdf ",
    event_header2:" The extraordinary shareholders' general meeting resolution notice for the first time",
    event_header2_:"http://www.neeq.com.cn/disclosure/2017/2017-02-07/1486453070_920199.pdf",
    event_header3:"Announcements of the extraordinary shareholders' general meeting for the first time",
    event_header3_:" http://www.neeq.com.cn/disclosure/2017/2017-01-11/1484125386_302627.pdf",
    event_header4:"Connection transaction announcement",
    event_header4_:"http://www.neeq.com.cn/disclosure/2017/2017-01-11/1484125268_012546.pdf",
	event_header5:"The third meeting of the board of directors resolution notice",
    event_header5_:"http://www.neeq.com.cn/disclosure/2017/2017-01-11/1484125264_234524.pdf",
	event_header6:"The general manager appointed public announcement",
    event_header6_:"http://www.neeq.com.cn/disclosure/2017/2017-01-11/1484125163_073027.pdf",
    pro_1:"Clothes",
    pro_1_:"Clothes",
    pro_1_1:"History of clothing remaining in the clothes on the sweet and spread out in dismay of camphor smell",
    pro_1_2:"We take the original, fashion, personality sequel to fashion a new chapter!",
    pro_1_3:"Make with lotus, lotus as the type.",
    pro_2:"Accessories",
    pro_2_:"Accessories",
    pro_2_1:"Clothes th or arm relaxed occlusions, pure and fresh and Laurie girl must belong to you! ",
    pro_2_2:"Frivolous knitting cardigan upper body effect is very great, no matter in the pitched or wear all does not occupy a space, still looks so thin, need not worry about bloated feeling. ",
    pro_2_3:"To help you build personal overall image including style definition, color analysis, dressing coordination and presence training, etc.",
    pro_3:"Digital",
    pro_3_:"Wearable",
    pro_3_1:"We do more than just a digital product, but a personality fashion way of life",
    pro_3_2:"Many say wearables will forever change the way we live, work and do business.",
    pro_3_3:"To remain competitive, your company might have to adopt a competitive wearables-integrated edge.",
    pro_4:"Household",
    pro_4_:"Items",
    pro_4_1:"The artists of that period regard building, furniture and household adornment as another kind of artistic creation. ",
    pro_4_2:"We will wholeheartedly sincere for you to create a different art, different worlds of the home environment."

}
